server:
  port: 8080
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-simple-consumer-movie-without-eureka
### #取消Ribbon使用Eureka
ribbon:
  eureka:
   enabled: false
#####配置Ribbon能访问 的微服务节点，多个节点用逗号隔开
microservice-simple-provider-user:
  ribbon:
    listOfServers: localhost:8090
