server:
  port: 8080
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
    prefer-ip-address: true
spring:
  application:
    name: micoservice-consumer-movie-ribbon-properties

microservice-simple-provider-user:
  ribbon:
    NFLoadBalancerRuleCla ssName: com.netflix.loadbalancer.RandomRule