server:
  port: 8090
#  port:8080

spring:
  jpa:
    database: mysql
    generate-ddl: false
    show-sql:  true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: microservice-simple-provider-user  #用小写
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}



